<?php

    include("class_tipo_pago.php");
    include("class_conexion.php");

    class tipo_pago_dal extends class_db {
        
        function __construct() {
            parent::__construct();
        }

        function __destruct() {
            parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function select_Tpagos() {
            $record = "SELECT * FROM tipo_pago ORDER BY tipo_pago ASC";
            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');

            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $list = array();
            $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new tipo_pago();

                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setId($row["id"]);
                $object->setTipo_pago($row['tipo_pago']);

                $counter++;
                $list[$counter] = $object;
                unset($object);
            }

            return $list;
        }
    
    }

?>