<?php
    include("class_presupuesto.php");
    include("class_conexion.php");

    class presupuesto_dal extends class_db{
        function __construct(){
            parent::__construct();
        }

        function __destruct(){
            parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function inserte_presupuesto($id_vehiculo, $op, $nivel, $concepto, $momh, $momp, $momm, $tot, $refacciones, $tmomh, $tmomp, $tmomm, $ttot, $trefacciones, $subtotal, $iva, $total, $fecha){
            $insert = "INSERT INTO presupuestos (id_vehiculo, op, nivel, concepto, momh, momp, momm, tot, refacciones, tmomh, tmomp, tmomm, ttot, trefacciones, subtotal, iva, total, fecha) VALUES (";
            $insert.= "'" . $id_vehiculo . "',";
            $insert.= "'" . $op . "',";
            $insert.= "'" . $nivel . "',";
            $insert.= "'" . $concepto . "',";
            $insert.= "'" . $momh . "',";
            $insert.= "'" . $momp . "',";
            $insert.= "'" . $momm . "',";
            $insert.= "'" . $tot . "',";
            $insert.= "'" . $refacciones . "',";
            $insert.= "'" . $tmomh . "',";
            $insert.= "'" . $tmomp . "',";
            $insert.= "'" . $tmomm . "',";
            $insert.= "'" . $ttot . "',";
            $insert.= "'" . $trefacciones . "',";
            $insert.= "'" . $subtotal . "',";
            $insert.= "'" . $iva . "',";
            $insert.= "'" . $total . "',";
            $insert.= "'" . $fecha . "')";

            $this->set_sql($insert);
            $this->db_conn->set_charset('utf8');

            mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

            if (mysqli_affected_rows($this->db_conn) == 1) {
                $inserted = 1;
            } else {
                $inserted = 0;
            }

            return $inserted;
        }

        function exist_presupuesto($id){
            $record = "SELECT id_vehiculo FROM presupuestos WHERE id_vehiculo = '$id'";

            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $total_result = mysqli_num_rows($result);
            if($total_result == 1){
                $re=1;
            }else{
                $re=0;
            }

            return $re;
        }

        function select_data($id){
            $record = "SELECT * FROM presupuestos WHERE id_vehiculo = '$id'";
            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $list = array();
            $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new presupuesto();
    
                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setOp($row["op"]);
                $object->setNivel($row['nivel']);
                $object->setConcepto($row['concepto']);
                $object->setMomh($row['momh']);
                $object->setMomp($row['momp']);
                $object->setMomm($row['momm']);
                $object->setTot($row['tot']);
                $object->setRefacciones($row['refacciones']);
                $object->setTmomh($row['tmomh']);
                $object->setTmomp($row['tmomp']);
                $object->setTmomm($row['tmomm']);
                $object->setTtot($row['ttot']);
                $object->setTrefacciones($row['trefacciones']);
                $object->setSubTotal($row['subtotal']);
                $object->setIva($row['iva']);
                $object->setTotal($row['total']);

    
                $counter++;
                $list[$counter] = $object;
                unset($object);
            }
    
            return $list;
        }

        function getOpCon($id){
            $record = "SELECT op, concepto FROM presupuestos WHERE id_vehiculo = '$id'";
            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $list = array();
            $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new presupuesto();
    
                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setOp($row["op"]);
                $object->setConcepto($row['concepto']);
    
                $counter++;
                $list[$counter] = $object;
                unset($object);
            }
    
            return $list;
        }

        function update_presupuesto($id_vehiculo, $op, $nivel, $concepto, $momh, $momp, $momm, $tot, $refacciones, $tmomh, $tmomp, $tmomm, $ttot, $trefacciones, $subtotal, $iva, $total){
            $update = 'UPDATE presupuestos SET ';
            $update .= "op = '$op', ";
            $update .= "nivel = '$nivel', ";
            $update .= "concepto = '$concepto', ";
            $update .= "momh = '$momh', ";
            $update .= "momp = '$momp', ";
            $update .= "momm = '$momm', ";
            $update .= "tot = '$tot', ";
            $update .= "refacciones = '$refacciones', ";
            $update .= "tmomh = '$tmomh', ";
            $update .= "tmomp = '$tmomp', ";
            $update .= "tmomm = '$tmomm', ";
            $update .= "ttot = '$ttot', ";
            $update .= "trefacciones = '$trefacciones', ";
            $update .= "subtotal = '$subtotal', ";
            $update .= "iva = '$iva', ";
            $update .= "total = '$total' ";
            $update .= "WHERE id_vehiculo = '$id_vehiculo'";

            //echo $update;

            $this->set_sql($update);
            $this->db_conn->set_charset('utf8');

            mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

            if (mysqli_affected_rows($this->db_conn) == 1) {
                $output = 1;
            } else {
                $output = 0;
            }

            return $output;
        }
    }

?>