<?php
    include("class_archivos.php");
    include("class_conexion.php");
    
    class archivos_dal extends class_db{

        function __construct(){
            parent::__construct();
        }

        function __destruct(){
            parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function insert_archivo($id_vehiculo, $ruta){
            $insert_archivo = "INSERT INTO archivos (id_vehiculo, ruta) VALUES (";
            $insert_archivo .= "'" . $id_vehiculo . "',";
            $insert_archivo .= "'" . $ruta . "')";

            //print $insert_archivo; exit;

            $this->set_sql($insert_archivo);
            $this->db_conn->set_charset('utf8');

            mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

            if (mysqli_affected_rows($this->db_conn) == 1) {
                $inserted = 1;
            } else {
                $inserted = 0;
            }

            return $inserted;

        }

        function exist_archivo($id){
            $record = "SELECT id_vehiculo FROM archivos WHERE id_vehiculo = '$id'";

            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $total_result = mysqli_num_rows($result);
            if($total_result == 1){
                $re=1;
            }else{
                $re=0;
            }

            return $re;
        }

        function ruta($id){
            $record = "SELECT ruta FROM archivos WHERE id_vehiculo = '$id'";

            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $list = array();
            $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new archivos();
    
                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setRuta($row["ruta"]);
    
                $counter++;
                $list[$counter] = $object;
                unset($object);
            }
    
            return $list;
        }
    }

?>