<?php
    include("class_refacciones.php");
    include("class_conexion.php");

    class refacciones_dal extends class_db{
        function __construct(){
            parent::__construct();
        }

        function __destruct(){
            parent::__destruct(); // TODO: Change the autogenerated stub
        }

        function exist_cotrefaccion($expediente){
            $record = "SELECT id_vehiculo FROM costrefacciones WHERE id_vehiculo = '$expediente'";

            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $total_result = mysqli_num_rows($result);
            if($total_result == 1){
                $re=1;
            }else{
                $re=0;
            }

            return $re;
        }
        
        function insert_cotrefacciones($expediente, $concepto, $cantidad, $nombreprov1, $nombreprov2, $nombreprov3, $proveedor1, $proveedor2, $proveedor3, $tpremier, $troto, $taldo, $tproveedorf, $tcostos, $tcostosf, $tfechapromesa, $tnumguia, $tcomentarios, $fecha){
            $insert = "INSERT INTO costrefacciones (id_vehiculo, concepto, cantidad, nombreprov1, nombreprov2, nombreprov3, proveedor1, proveedor2, proveedor3, tproveedor1, tproveedor2, tproveedor3, proveedorfinal, costo, costofinal, fecha_promesa, num_guia, comentarios, fecha) VALUES (";
            $insert.= "'" . $expediente . "',";
            $insert.= "'" . $concepto . "',";
            $insert.= "'" . $cantidad . "',";
            $insert.= "'" . $nombreprov1 . "',";
            $insert.= "'" . $nombreprov2 . "',";
            $insert.= "'" . $nombreprov3 . "',";
            $insert.= "'" . $proveedor1 . "',";
            $insert.= "'" . $proveedor2 . "',";
            $insert.= "'" . $proveedor3 . "',";
            $insert.= "'" . $tpremier . "',";
            $insert.= "'" . $troto . "',";
            $insert.= "'" . $taldo . "',";
            $insert.= "'" . $tproveedorf . "',";
            $insert.= "'" . $tcostos . "',";
            $insert.= "'" . $tcostosf . "',";
            $insert.= "'" . $tfechapromesa . "',";
            $insert.= "'" . $tnumguia . "',";
            $insert.= "'" . $tcomentarios . "',";
            $insert.= "'" . $fecha . "')";

            $this->set_sql($insert);
            $this->db_conn->set_charset('utf8');

            mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

            if (mysqli_affected_rows($this->db_conn) == 1) {
                $inserted = 1;
            } else {
                $inserted = 0;
            }

            return $inserted;
        }

        function selcet_data($id){
            $result = "SELECT * FROM costrefacciones WHERE id_vehiculo = '$id'";
            $this->set_sql($result);
            $this->db_conn->set_charset('utf8');

            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $list = array();
            $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new refacciones();
    
                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setConcepto($row["concepto"]);
                $object->setCantidad($row['cantidad']);
                $object->setNombreprov1($row['nombreprov1']);
                $object->setNombreprov2($row['nombreprov2']);
                $object->setNombreprov3($row['nombreprov3']);
                $object->setProveedor1($row['proveedor1']);
                $object->setProveedor2($row['proveedor2']);
                $object->setProveedor3($row['proveedor3']);
                $object->setTProveedor1($row['tproveedor1']);
                $object->setTProveedor2($row['tproveedor2']);
                $object->setTProveedor3($row['tproveedor3']);
                $object->setProveedorFinal($row['proveedorfinal']);
                $object->setCosto($row['costo']);
                $object->setCostofinal($row['costofinal']);
                $object->setFechaPromesa($row['fecha_promesa']);
                $object->setNumGuia($row['num_guia']);
                $object->setFechaLlegada($row['fecha_llegada']);
                $object->setComentarios($row['comentarios']);
    
                $counter++;
                $list[$counter] = $object;
                unset($object);
            }
    
            return $list;
        }

        function exist_expediente($expediente){
            $record = "SELECT id FROM vehiculo WHERE id = '$expediente'";

            $this->set_sql($record);
            $this->db_conn->set_charset('utf8');
    
            $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
            $total_result = mysqli_num_rows($result);
            if($total_result == 1){
                $re=1;
            }else{
                $re=0;
            }

            return $re;
        }
    }
?>