<?php

include("class_personal.php");
include("class_conexion.php");

class personal_dal extends class_db
{
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    function select_personalH(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 1 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalPrep(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 2 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalPin(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 3 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalArm(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 4 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalDet(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 5 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalMeca(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 6 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }

    function select_personalLava(){
        $select_all = "SELECT id, nombre FROM personal WHERE id_area = 7 ORDER BY nombre";
        //print $select_all; exit;

        $this->set_sql($select_all);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new personal();

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            $object->setId($row["id"]);
            $object->setNombre($row["nombre"]);

            $counter++;
            $list[$counter] = $object;
            unset($object);
        }

        return $list;
    }
  
}

?>