<?php

include("class_areas.php");
include("class_conexion.php");

class areas_dal extends class_db
{
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

  
}

?>