<?php

include("class_admin.php");
include("class_conexion.php");

class admin_dal extends class_db
{
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

   //insert
    function insert_admin($id, $usuario, $psdw)
    {
        $insert_customer = "INSERT INTO usuarios(id, usuario, psdw) VALUES(";
        $insert_customer .= "'" . $id . "',";
        $insert_customer .= "'" . $usuario . "',";
        $insert_customer .= "'" . $psdw . "',";
        //print $insert_customer; exit;

        $this->set_sql($insert_customer);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $inserted = 1;
        } else {
            $inserted = 0;
        }

        return $inserted;
    }

    //update
    function update_admin( $id, $psdw, $usuario)
    {
        $update_customer = "UPDATE usuarios SET ";
        $update_customer .= "id = '" . $id . "',";
        $update_customer .= "usuario = '" . $usuario . "',";
        $update_customer .= "psdw = '" . $psdw . "',";
        //print $insert_customer; exit;

        $this->set_sql($update_customer);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $updated = 1;
        } else {
            $updated = 0;
        }

        return $updated;
    }

    //delete
    function delete_admin($id_cli)
    {
        $delete_customer = "DELETE FROM usuarios WHERE id = $id";
        //print $delete_customer; exit;

        $this->set_sql($delete_customer);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $deleted = 1;
        } else {
            $deleted = 0;
        }

        return $deleted;
    }

    //select all
    function select_admin()
    {
        $select_customers = "SELECT * FROM usuarios";
        //print $select_customers; exit;

        $this->set_sql($select_customers);
        $this->db_conn->set_charset('utf8');

        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);

        $counter = 0;
        while ($row = mysqli_fetch_assoc($result)) {
            $object = new usuarios;

            /*los nombres entre comillas son los nombres de las columnas de las tablas
            se usan los set para enviar el valor al objeto y con el get obtenemos el valor
            donde lo invoquemos*/
            
            $object->setRfc($row["id"]);
            $object->setNombre($row["usuario"]);
            $object->setPaterno($row["psdw"]);
        
            $counter++;
            $list[$counter] = $object;
            unset($object);
        }
        return $list;
    }

    //exists cliente
    function exists_usuario($user,$pswd)
    {
        $pswd = md5($pswd);
        //return $psdw;
        $user = mysqli_real_escape_string($this->db_conn, $user);
        $pswd = mysqli_real_escape_string($this->db_conn, $pswd);
        //return $user;

        $sql_exists = "SELECT pswd FROM usuarios WHERE usuario = '$user' and pswd = '$pswd'";
        //return $sql_exists;

        $this->set_sql($sql_exists);
        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_result = mysqli_num_rows($result);
        if($total_result == 1){
            $re=1;
        }else{
            $re=0;
        }

        return $re;

    }
    
    function tipo_usuario($user,$pswd)
    {
        $pswd = md5($pswd);
        //return $psdw;
        $user = mysqli_real_escape_string($this->db_conn, $user);
        $pswd = mysqli_real_escape_string($this->db_conn, $pswd);
        //return $user;

        $sql_exists = "SELECT tipo FROM usuarios WHERE usuario = '$user' and pswd = '$pswd'";
        //return $sql_exists;

        $this->set_sql($sql_exists);
        $result = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $list = array();
        $counter = 0;
            while ($row = mysqli_fetch_assoc($result)) {
                $object = new admin();
    
                /*los nombres entre comillas son los nombres de las columnas de las tablas
                se usan los set para enviar el valor al objeto y con el get obtenemos el valor
                donde lo invoquemos*/
                $object->setTipo($row["tipo"]);
    
                $counter++;
                $list[$counter] = $object;
                unset($object);
            }
    
            return $list;
    }

    function insert_login($nombre, $puesto, $fecha, $hora){
        $insert_customer = "INSERT INTO login(nombre, puesto, fecha, hora) VALUES(";
        $insert_customer .= "'" . $nombre . "',";
        $insert_customer .= "'" . $puesto . "',";
        $insert_customer .= "'" . $fecha . "',";
        $insert_customer .= "'" . $hora . "')";
        //print $insert_customer; exit;

        $this->set_sql($insert_customer);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $inserted = 1;
        } else {
            $inserted = 0;
        }

        return $inserted;
    }

    function insert_logout($nombre, $puesto, $fecha, $hora){
        $insert_customer = "INSERT INTO logout(nombre, puesto, fecha, hora) VALUES(";
        $insert_customer .= "'" . $nombre . "',";
        $insert_customer .= "'" . $puesto . "',";
        $insert_customer .= "'" . $fecha . "',";
        $insert_customer .= "'" . $hora . "')";
        //print $insert_customer; exit;

        $this->set_sql($insert_customer);
        $this->db_conn->set_charset('utf8');

        mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));

        if (mysqli_affected_rows($this->db_conn) == 1) {
            $inserted = 1;
        } else {
            $inserted = 0;
        }

        return $inserted;
    }
}